### ISSUE TITLE
Extension doesn't install PHP redis module for PHP 7.x

### ISSUE THREAD

**Issue by gonzomir** [Chassis/redis#10]
The PHP extension is not installed because the package name in the `init.pp` file doesn't match the APT package name.

1. What operating system do you use?
    Ubuntu 20.04

2. What version of Vagrant are you running?
    2.2.15

3. Are you using VirtualBox or VMWare and which version are you using?
    VirtualBox

4. Do you have a custom YAML file? If so, what does it contain?
    I'm using Altis Local Chassis.

5. Do you have any Chassis other extensions installed? If so, what are they?
    I'm using Altis Local Chassis.

**Comment by BronsonQuick** [comment]
Fixed in #10.
